Microsoft (R) Macro Assembler Version 5.00                  4/23/26 13:33:40
                                                             Page     1-1



Es.ASM(1): warning A4085: End of file, no END directive
Microsoft (R) Macro Assembler Version 5.00                  4/23/26 13:33:40
                                                             Page     1-1


				 
Es.ASM(1): warning A4085: End of file, no END directive
Microsoft (R) Macro Assembler Version 5.00                  4/23/26 13:33:40
                                                             Symbols-1


Symbols:            

                N a m e         	Type	 Value	 Attr

@FILENAME  . . . . . . . . . . .  	TEXT  Es		


      0 Source  Lines
      1 Total   Lines
      1 Symbols

  51352 + 465192 Bytes symbol space free

      1 Warning Errors
      1 Severe  Errors
